mystr = "Bhola is a good boy"
"""print(len(mystr))
print(mystr[0:5:2])
print(mystr[:5])
print(mystr[0:])
print(mystr[0::2])
print(mystr[:])
print(mystr[::])
print(mystr[:-5])
print(mystr[::-1])"""
print(type(mystr))
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.count("o"))
print(mystr.upper())
print(mystr.find("is"))
print(mystr.replace("a", 'an'))